name: Build and Push Gitea Custom Image

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Gitea version from Dockerfile
        id: version
        run: |
          # 从 Dockerfile 的 FROM 行提取 tag，例如: FROM docker.gitea.com/gitea:1.24.3
          GITEA_VERSION=$(grep -oP '(?<=FROM docker\.gitea\.com/gitea:).*' Dockerfile)
          if [ -z "$GITEA_VERSION" ]; then
            echo "Unable to extract Gitea version from Dockerfile" >&2
            exit 1
          fi
          echo "version=$GITEA_VERSION" >> "$GITHUB_OUTPUT"

      - name: Derive short commit SHA
        id: meta
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}-${{ steps.meta.outputs.short_sha }}
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
          platforms: linux/arm64