name: Build and Push Gitea Custom Image

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Gitea version from Dockerfile
        id: version
        run: |
          GITEA_VERSION=$(grep -oP '(?<=ARG GITEA_VERSION=).*' Dockerfile)
          echo "version=$GITEA_VERSION" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64